version: "3.7"

services:
  yamdb_db:
    image: postgres:13.0-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ../.env

  yamdb_backend:
#    image: chemisto/yamdb_final:latest
    build:
        context: ../
    env_file:
      - ../.env
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    ports:
      - "8000:8000"
    depends_on:
      - yamdb_db
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py collectstatic --noinput
      && gunicorn --bind 0.0.0.0:8000 api_yamdb.wsgi:application"



  yamdb_gateway:
    image: nginx:1.21.3-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    ports:
      - "80:80"
    depends_on:
      - yamdb_backend

volumes:
  db_value:
  static_value:
  media_value:
